### PR TITLE
Improve Login and Sign-Up Page Design

### PR DESCRIPTION
**Pull request by Anjali1241**

### CODE REVIEW

**Comment by Anjali1241** [comment]
@Princy-patel 
Could you please review the pages and provide your suggestions?
below is screenshot:
image

image

**Comment by Princy-patel** [comment]
> @Princy-patel Could you please review the pages and provide your suggestions? below is screenshot: image
> 
> image

hi, @Anjali1241 
Thanks for adding the background image! But it feels a bit heavy and might not align with our design vision. 
Could we consider finding a different approach or going back to the shadow effect? Let me know your thoughts.

**Review by Princy-patel — CHANGES_REQUESTED** [review]
@Anjali1241 ,
Let's create a common modal and implement both Login and Sign-In features within that modal. We don't need separate pages for this; just a single modal will suffice.

**Comment by Anjali1241** [comment]
will do that @Princy-patel

**Pull request merged**
